# Generated by Django 4.2.1 on 2023-05-23 17:47

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinformations',
            fields=[
                ('course_id', models.CharField(db_column='Course_ID', max_length=104, primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='Course_Name', max_length=200, null=True)),
                ('level_of_difficulties', models.IntegerField(null=True)),
                ('objectiveOfCourse', models.CharField(db_column='CourseObjective', max_length=200, null=True)),
                ('lanaguage', models.CharField(db_column='Language', max_length=200, null=True)),
                ('tottal_credit_hour', models.IntegerField()),
                ('programs', models.CharField(choices=[('Bachelor degree', 'Bachelor Degree'), ('Master Degree', 'Master Degree')], max_length=100)),
            ],
            options={
                'db_table': 'courseinformations',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('firstname', models.CharField(db_column='FirstName', max_length=140)),
                ('middlename', models.CharField(db_column='MiddleName', max_length=104)),
                ('lastname', models.CharField(db_column='LastName', max_length=104)),
                ('username', models.CharField(db_column='UserName', default='', max_length=104)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_column='Gender', default='private', max_length=6)),
                ('phonenumber', models.CharField(db_column='PhoneNumber', max_length=103)),
                ('address', models.CharField(db_column='Country', max_length=104)),
                ('email', models.EmailField(max_length=55, null=True)),
                ('employeeid', models.CharField(db_column='EmployeeID', max_length=104, primary_key=True, serialize=False)),
                ('userObject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='MainCoursecontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('courseid', models.ForeignKey(db_column='MaincourseId', on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.courseinformations')),
            ],
            options={
                'db_table': 'Maincoursecontent',
            },
        ),
        migrations.CreateModel(
            name='tableofContentOfMainCourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, null=True)),
                ('courseid', models.ForeignKey(db_column='courseId', on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.courseinformations')),
            ],
            options={
                'db_table': 'tableOfContentofCourseInformation',
                'unique_together': {('courseid', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='RoleInSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Registrar', 'Registrar'), ('Admin', 'Admin')], max_length=150)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PriceForDepartements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='MainCoursecontentdetailcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(db_column='PDF', upload_to='Files/MainCourseAsset')),
                ('audio', models.FileField(db_column='Audio', upload_to='Files/MainCourseAsset')),
                ('video', models.FileField(db_column='Video', upload_to='Files/MainCourseAsset')),
                ('notes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_column='Notes', null=True)),
                ('courseid', models.ForeignKey(db_column='courseId', on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.maincoursecontent')),
            ],
            options={
                'db_table': 'Maincoursecontentdetailcontent',
            },
        ),
        migrations.AddField(
            model_name='maincoursecontent',
            name='tableofcontent',
            field=models.ForeignKey(blank=True, db_column='tableOFContent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.tableofcontentofmaincourseinformation'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_faculty_name', models.CharField(max_length=500)),
                ('facult_adminstrator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='departement_head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.faculty'),
        ),
        migrations.AddField(
            model_name='courseinformations',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.department'),
        ),
        migrations.AlterUniqueTogether(
            name='maincoursecontent',
            unique_together={('courseid', 'tableofcontent')},
        ),
    ]
