# Generated by Django 4.2.1 on 2023-05-21 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('School_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userObject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roleinschool',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_Admin.employee'),
        ),
    ]
