# Generated by Django 4.2.1 on 2023-05-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformations',
            name='time_required_to_complete',
        ),
    ]
