# Generated by Django 4.2.1 on 2023-05-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Admin', '0003_alter_courseinformations_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceForDepartements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.courseinformations')),
            ],
        ),
    ]
