# Generated by Django 4.2.1 on 2023-05-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_Admin', '0004_pricefordepartements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefordepartements',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School_Admin.department'),
        ),
    ]
